# --- Configuration Fixe ---
# Chemins des sources
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Exclusions techniques (node_modules, dossiers de build, tests)
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.test.js, **/*.spec.js, **/*.test.jsx

# Rapports de tests et couverture (Javascript)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# URL du serveur (si elle est fixe dans ton infrastructure)
sonar.host.url=http://sonarqube:9000